spring:
  redis:
    host: 134.175.210.2533566
    port: 65379
    password: 'cdMall@321'
    database: 0
    pool:
      max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
#    sentinel:
#      master: mymaster
#      nodes: node1.td-k8s.com:24379

db:
  ds:
    write:
      common: #通用写
        url: jdbc:mysql://134.175.210.250:3306/cd-system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: cdmall
        password: 'cdMall@321'
    read:
      common: #通用读
        url: jdbc:mysql://134.175.210.250:3306/cd-system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: cdmall
        password: 'cdMall@321'

app:
  #是否为web站点, 默认false
  web.project: false
  performance.log: NOTSET
  performance.log.ignore:
    # 不打印sql日志
    sql: true
    # 不打印mq日志
    mq: true
  okhttp:
    read.timeout: 3000
    connect.timeout: 3000
    write.timeout: 10000
    #最大空闲连接数
    max.idle: 5
    #空闲连接存活时间
    alive.duration: 300
       
qiniu:
    access:
        key: LAI-hbo6DnM_A9iIuDycii-t5yj3LquE169jjah4
    secret:
        key: XfHOMrGoVM6pQXL45P0RP02C_eChhtGZRXbvMe3w
    bucket:
        name: cdmall
        domain: http://cdqn.zhimeiplus.com
    token:
        expires: 3600

ribbon:
    # 默认的连接超时时间, Feign会优先读取这个配置
    ConnectTimeout: 30000
    # 默认的读取超时时间, Feign会优先读取这个配置
    ReadTimeout: 30000
hystrix:
    # hystrix执行命令的默认超时时间, 超过这个时间feign调用将抛出HystrixRuntimeException
    command.default.execution.isolation.thread.timeoutInMilliseconds: 300000
    # 线程池大小, Feign每个类使用不同的线程池
    threadpool.default.coreSize: 100 
minapp:
  shop:
    appid: wxcb7e2f302876fcd1
    appsecret: 321e8e7ec7a0029c920c4764c4fd5c70
    name: 草动消费端
    version: 1.1.22
    versiondesc: 草动消费端
    templateid: 41
    address: pages/index/index
    tag: 商城
    firstclass: 工具
    secondclass: 办公
    thirdclass:
    firstid: 287
    secondid: 298
    thirdid:
    title: 首页
    whitelist: wx80de0e4d0fde04b3, wx5abce7440ec26fa8, wx25c15e3d8ff82a7f, wx226baab87d94553d, wxbdac592c53628387, wxafaaaa1002a56f89, wx1f035e106d0959cd, wx88d4bf99ce09e060, wx879f38a9e13bd510
    requestdomain: https://api.icaodong.com,https://apiuat.icaodong.com
    wsrequestdomain:
    uploaddomain: https://up.qbox.me
    downloaddomain: https://qiniu.icaodong.com,https://api.icaodong.com
    webviewdomain: https://api.icaodong.com,https://apiuat.icaodong.com
    proddomain:
      webviewdomain: https://api.icaodong.com/miniapp
      uploaddomain: https://up.qbox.me

wx:
  pay:
    authorize:
      url: https://api.icaodong.com  
